// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOADED_SUCCESS = 'LOADED_SUCCESS'
export const LOADED_FAIL = 'LOADED_FAIL'
export const LOGOUT = 'LOGOUT'

// PROFILE
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'

// LOGS
export const GET_LOGS = 'GET_LOGS'
export const CLEAR_LOGS = 'CLEAR_LOGS'
export const ADD_LOG = 'ADD_LOG'
export const UPDATE_LOG = 'UPDATE_LOG'

// EXERCISES
export const GET_EXERCISES = 'GET_EXERCISES'
export const CLEAR_EXERCISES = 'CLEAR_EXERCISES'
